import type { Source } from '@/lib/relay';

export type { Source };

/**
 * Provenance stamp on every reading.
 *
 * `badge` means a real ESP32-C3 is attached and this number came off its serial
 * console. `esp32c3` means a real ESP32-C3 node answered over WiFi: a VENDX node
 * running firmware-vendor and registered with the relay, or a presence-node badge
 * the relay polls. `simulator` means software. Real hardware and software must
 * never be mistaken for each other, so this is stamped on every row and never hidden.
 */
const TITLE: Record<Source, string> = {
  badge: 'Read from the attached ESP32-C3 badge',
  esp32c3: 'Live from an ESP32-C3 node over WiFi: a VENDX node registered with the relay, or a presence-node badge the relay polls',
  simulator: 'Generated by the simulator',
};

export function SourceBadge({ source }: { source: Source }) {
  const isHardware = source !== 'simulator';
  return (
    <span
      className={`plate inline-flex items-center gap-1.5 rounded-[2px] border px-1.5 py-0.5 ${
        isHardware
          ? 'border-ink/40 text-ink'
          : 'border-rule text-ink-muted'
      }`}
      title={TITLE[source] ?? source}
    >
      <span
        aria-hidden="true"
        className={`h-1.5 w-1.5 rounded-full ${isHardware ? 'bg-ink ' : 'bg-ink-muted'}`}
      />
      {source}
    </span>
  );
}
