/**
 * Provenance stamp on every reading.
 *
 * `badge` means a real ESP32-C3 is attached and this number came off its serial
 * console. `esp32c3` means a real ESP32-C3 node answered over WiFi (a vendor
 * node selling directly, or a presence-node badge the relay polls). `simulator`
 * means software. They must never be mistaken for each other, so this is stamped
 * on every row and never hidden.
 */
export type Source = 'badge' | 'simulator' | 'esp32c3';

export function SourceBadge({ source }: { source: Source }) {
  const isBadge = source !== 'simulator';
  return (
    <span
      className={`plate inline-flex items-center gap-1.5 rounded-[2px] border px-1.5 py-0.5 ${
        isBadge
          ? 'border-ink/40 text-ink'
          : 'border-rule text-ink-muted'
      }`}
      title={source === 'badge' ? 'Read from the attached ESP32-C3 badge over its serial console' : source === 'esp32c3' ? 'Live from an ESP32-C3 node over its own WiFi interface' : 'Generated by the simulator'}
    >
      <span
        aria-hidden="true"
        className={`h-1.5 w-1.5 rounded-full ${isBadge ? 'bg-ink ' : 'bg-ink-muted'}`}
      />
      {source}
    </span>
  );
}
