import { test, expect } from '@playwright/test';

/*
  Relay-UP coverage.

  routes.spec.ts runs with no relay, so every page only ever proves its empty
  state. That is how a contract mismatch between lib/relay.ts and the relay's
  actual response shapes shipped unnoticed: /devices, /devices/[id] and
  /marketplace all crashed the moment the relay was running.

  These tests SKIP (not pass) when the relay is unreachable, so a relay-down run
  stays green and honest, and a relay-up run actually exercises the join.
*/

const RELAY = process.env.NEXT_PUBLIC_RELAY_URL ?? 'http://localhost:3402';

async function relayUp(): Promise<boolean> {
  try {
    const r = await fetch(`${RELAY}/health`, { signal: AbortSignal.timeout(1500) });
    return r.ok;
  } catch {
    return false;
  }
}

test.describe('with relay-proxy running', () => {
  test.beforeEach(async () => {
    test.skip(!(await relayUp()), `relay-proxy not reachable at ${RELAY}`);
  });

  test('the agent console asks a visitor to sign in before it will spend', async ({ page }) => {
    // The full signed-in handshake (a real devnet purchase) lives in auth.spec.ts.
    const errors: string[] = [];
    page.on('pageerror', (e) => errors.push(e.message));
    await page.goto('/agent', { waitUntil: 'networkidle' });
    await expect(page.getByRole('button', { name: /run handshake/i })).toHaveCount(0);
    await expect(page.getByRole('link', { name: /sign in to run|read the protocol/i })).toBeVisible();
    await expect(page.getByRole('list', { name: /handshake steps/i }).getByRole('listitem')).toHaveCount(9);
    expect(errors).toEqual([]);
  });

  for (const path of ['/', '/devices', '/marketplace', '/policy', '/ledger', '/protocol']) {
    test(`${path} renders populated with no server error`, async ({ page }) => {
      const res = await page.goto(path, { waitUntil: 'networkidle' });
      expect(res?.status(), `${path} returned ${res?.status()}`).toBeLessThan(500);
      await expect(page.locator('h1').first()).toBeVisible();
      // The relay is up, so no page may show its offline state.
      await expect(page.getByText(/no relay link/i)).toHaveCount(0);
    });
  }

  test('/devices/[id] renders the real device', async ({ page }) => {
    const list = await (await fetch(`${RELAY}/api/devices`)).json() as { devices: { id: string }[] };
    const id = list.devices[0]?.id;
    test.skip(!id, 'relay reports no devices');
    const res = await page.goto(`/devices/${encodeURIComponent(id!)}`, { waitUntil: 'networkidle' });
    expect(res?.status()).toBeLessThan(500);
    await expect(page.locator('h1').first()).toContainText(id!);
  });

  test('every reading is stamped badge or simulator, never neither', async ({ page }) => {
    await page.goto('/devices', { waitUntil: 'networkidle' });
    const stamps = page.locator('[title^="Read from the attached"], [title^="Generated by the simulator"]');
    expect(await stamps.count()).toBeGreaterThan(0);
  });
});
